### ISSUE TITLE
Allow default conditions override

### ISSUE THREAD

**Issue by dmnsgn** [sagargurtu/normalize-exports#1]
At the moment, defaultConditions are always added which makes it impossible to remove "node" for instance.

https://github.com/sagargurtu/normalize-exports/blob/e39bac220a5e249222aa903066a277637853bc06/src/index.ts#L215

It would be great to either add a condition override options or use options.conditions as the only source of conditions.

Also exporting all functions (`checkExportsConfiguration`, `matchConditions`, `expandWildcardEntry`, `getFlattenedEntries`...) would be very useful and an alternative if you don't want to change how options conditions are handled.

**Comment by sagargurtu** [comment]
Fixed by 44d7b8e5c9455653f835e53e5b0e34079c1ec7d6
